In [1]:
import pandas as pd
df=pd.read_csv("Support_Ticket.csv")

In [21]:
df.head()

,subject,body,type,queue,priority,language
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Incident,Technical Support,high,de
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Incident,Technical Support,high,en
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Request,Returns and Exchanges,medium,en
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Request,Billing and Payments,low,en
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Problem,Sales and Pre-Sales,medium,en

In [3]:
df.shape

(28587, 6)

In [4]:
df.isnull().sum()

subject     3838
body           0
type           0
queue          0
priority       0
language       0
dtype: int64

In [5]:
df = df.dropna(subset=['subject'])

In [6]:
df.isnull().sum()

subject     0
body        0
type        0
queue       0
priority    0
language    0
dtype: int64

In [7]:
df.shape

(24749, 6)

In [16]:
df['type'].value_counts()

type
Incident    9951
Request     7081
Problem     5233
Change      2484
Name: count, dtype: int64

In [17]:
df['queue'].value_counts()

queue
Technical Support                  7260
Product Support                    4563
Customer Service                   3733
IT Support                         2943
Billing and Payments               2427
Returns and Exchanges              1226
Service Outages and Maintenance    1024
Sales and Pre-Sales                 763
Human Resources                     473
General Inquiry                     337
Name: count, dtype: int64

In [18]:
df['priority'].value_counts()

priority
medium    9978
high      9655
low       5116
Name: count, dtype: int64

In [19]:
df['language'].value_counts()

language
en    13731
de    11018
Name: count, dtype: int64

In [22]:
df = df[df['language'] == 'en'].copy()

In [24]:
df.shape

(13731, 6)

In [26]:
df['type'].value_counts()

type
Incident    5531
Request     3929
Problem     2874
Change      1397
Name: count, dtype: int64

In [27]:
df['queue'].value_counts()

queue
Technical Support                  3971
Product Support                    2608
Customer Service                   2045
IT Support                         1609
Billing and Payments               1349
Returns and Exchanges               686
Service Outages and Maintenance     581
Sales and Pre-Sales                 410
Human Resources                     285
General Inquiry                     187
Name: count, dtype: int64

In [28]:
df['priority'].value_counts()

priority
medium    5595
high      5304
low       2832
Name: count, dtype: int64

In [31]:
df.drop(columns=["language"], inplace=True)

In [34]:
df.head()

,subject,body,type,queue,priority
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Incident,Technical Support,high
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Request,Returns and Exchanges,medium
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Request,Billing and Payments,low
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Problem,Sales and Pre-Sales,medium
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Request,Technical Support,high

In [35]:
import re

def clean_text(text):
    text = str(text).lower()

    # Remove newline and tab characters
    text = re.sub(r'[\n\r\t]+', ' ', text)

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Remove email addresses
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [36]:
X = df[['subject', 'body', 'type']].copy()

X['subject'] = X['subject'].apply(clean_text)
X['body'] = X['body'].apply(clean_text)

In [37]:
X['text'] = X['subject'] + ' ' + X['body']

In [46]:
X.head()

,subject,body,type,text
1,account disruption,dear customer support team n ni am writing to ...,Incident,account disruption dear customer support team ...
2,query about smart home system integration feat...,dear customer support team n ni hope this mess...,Request,query about smart home system integration feat...
3,inquiry regarding invoice details,dear customer support team n ni hope this mess...,Request,inquiry regarding invoice details dear custome...
4,question about marketing agency software compa...,dear support team n ni hope this message reach...,Problem,question about marketing agency software compa...
5,feature query,dear customer support n ni hope this message r...,Request,feature query dear customer support n ni hope ...

In [ ]:
stratify_label = (
    df['queue'].astype(str) + '_' +
    df['priority'].astype(str)
)

In [41]:
y_queue=df['queue']
y_priority=df['priority']

In [42]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_queue_train, y_queue_test, y_priority_train, y_priority_test = train_test_split(
    X,
    y_queue,
    y_priority,
    test_size=0.2,
    random_state=42,
    stratify=stratify_label
)

In [58]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95,
    sublinear_tf=True
)


X_train_text = tfidf.fit_transform(X_train['text'])
X_test_text = tfidf.transform(X_test['text'])

In [59]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown='ignore',
    sparse_output=True
)

X_train_type = encoder.fit_transform(X_train[['type']])
X_test_type = encoder.transform(X_test[['type']])

In [63]:
X_train.shape

(10984, 4)

In [64]:
X_test.shape

(2747, 4)

In [65]:
from scipy.sparse import hstack

X_train_final = hstack([
    X_train_text,
    X_train_type
])

X_test_final = hstack([
    X_test_text,
    X_test_type
])

In [66]:
from sklearn.linear_model import LogisticRegression

queue_model = LogisticRegression(
    max_iter=1000,
    C=1.0,
    class_weight='balanced'
)

priority_model = LogisticRegression(
    max_iter=1000,
    C=1.0,
    class_weight='balanced'
)

In [67]:
queue_model.fit(X_train_final, y_queue_train)

priority_model.fit(X_train_final, y_priority_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

In [68]:
from sklearn.svm import LinearSVC

queue_svm = LinearSVC(
    C=1.0,
    class_weight='balanced'
)

priority_svm = LinearSVC(
    C=1.0,
    class_weight='balanced'
)

In [69]:
queue_svm.fit(X_train_final, y_queue_train)

priority_svm.fit(X_train_final, y_priority_train)

LinearSVC(class_weight='balanced')

In [70]:
from sklearn.naive_bayes import MultinomialNB

queue_nb = MultinomialNB()
priority_nb = MultinomialNB()

In [71]:
queue_nb.fit(X_train_final, y_queue_train)

priority_nb.fit(X_train_final, y_priority_train)

MultinomialNB()

In [ ]:


queue_lr_pred = queue_model.predict(X_test_final)
priority_lr_pred = priority_model.predict(X_test_final)


queue_svm_pred = queue_svm.predict(X_test_final)
priority_svm_pred = priority_svm.predict(X_test_final)



queue_nb_pred = queue_nb.predict(X_test_final)
priority_nb_pred = priority_nb.predict(X_test_final)

In [82]:
from sklearn.metrics import classification_report

# =========================
# QUEUE - ALL MODELS
# =========================

print("\n" + "="*80)
print("QUEUE - LOGISTIC REGRESSION")
print("="*80)
print(classification_report(
    y_queue_test,
    queue_lr_pred,
    digits=4,
    zero_division=0
))

print("\n" + "="*80)
print("QUEUE - LINEAR SVM")
print("="*80)
print(classification_report(
    y_queue_test,
    queue_svm_pred,
    digits=4,
    zero_division=0
))

print("\n" + "="*80)
print("QUEUE - NAIVE BAYES")
print("="*80)
print(classification_report(
    y_queue_test,
    queue_nb_pred,
    digits=4,
    zero_division=0
))


# =========================
# PRIORITY - ALL MODELS
# =========================

print("\n" + "="*80)
print("PRIORITY - LOGISTIC REGRESSION")
print("="*80)
print(classification_report(
    y_priority_test,
    priority_lr_pred,
    digits=4,
    zero_division=0
))

print("\n" + "="*80)
print("PRIORITY - LINEAR SVM")
print("="*80)
print(classification_report(
    y_priority_test,
    priority_lr_pred,
    digits=4,
    zero_division=0
))

print("\n" + "="*80)
print("PRIORITY - NAIVE BAYES")
print("="*80)
print(classification_report(
    y_priority_test,
    priority_nb_pred,
    digits=4,
    zero_division=0
))

================================================================================
QUEUE - LOGISTIC REGRESSION
================================================================================
                                 precision    recall  f1-score   support

           Billing and Payments     0.7429    0.7704    0.7564       270
               Customer Service     0.4108    0.4279    0.4192       409
                General Inquiry     0.3559    0.5676    0.4375        37
                Human Resources     0.3523    0.5439    0.4276        57
                     IT Support     0.4195    0.4938    0.4536       322
                Product Support     0.5039    0.3716    0.4278       522
          Returns and Exchanges     0.4059    0.5036    0.4495       137
            Sales and Pre-Sales     0.2910    0.6707    0.4059        82
Service Outages and Maintenance     0.5669    0.7672    0.6520       116
              Technical Support     0.5749    0.4440    0.5011       795

                       accuracy                         0.4929      2747
                      macro avg     0.4624    0.5561    0.4931      2747
                   weighted avg     0.5105    0.4929    0.4931      2747


================================================================================
QUEUE - LINEAR SVM
================================================================================
                                 precision    recall  f1-score   support

           Billing and Payments     0.8212    0.8333    0.8272       270
               Customer Service     0.5341    0.5355    0.5348       409
                General Inquiry     0.6176    0.5676    0.5915        37
                Human Resources     0.5556    0.5263    0.5405        57
                     IT Support     0.5190    0.5528    0.5353       322
                Product Support     0.6000    0.5575    0.5780       522
          Returns and Exchanges     0.5664    0.5912    0.5786       137
            Sales and Pre-Sales     0.4483    0.6341    0.5253        82
Service Outages and Maintenance     0.6917    0.7931    0.7390       116
              Technical Support     0.6570    0.6239    0.6400       795

                       accuracy                         0.6134      2747
                      macro avg     0.6011    0.6215    0.6090      2747
                   weighted avg     0.6159    0.6134    0.6137      2747


================================================================================
QUEUE - NAIVE BAYES
================================================================================
                                 precision    recall  f1-score   support

           Billing and Payments     0.9133    0.5074    0.6524       270
               Customer Service     0.2727    0.4694    0.3450       409
                General Inquiry     0.0000    0.0000    0.0000        37
                Human Resources     0.0000    0.0000    0.0000        57
                     IT Support     0.5349    0.0714    0.1260       322
                Product Support     0.3466    0.2337    0.2792       522
          Returns and Exchanges     0.0000    0.0000    0.0000       137
            Sales and Pre-Sales     0.0000    0.0000    0.0000        82
Service Outages and Maintenance     1.0000    0.0172    0.0339       116
              Technical Support     0.3930    0.7396    0.5133       795

                       accuracy                         0.3873      2747
                      macro avg     0.3461    0.2039    0.1950      2747
                   weighted avg     0.4149    0.3873    0.3333      2747


================================================================================
PRIORITY - LOGISTIC REGRESSION
================================================================================
              precision    recall  f1-score   support

        high     0.6327    0.6321    0.6324      1060
         low     0.4811    0.5599    0.5175       568
      medium     0.6154    0.5648    0.5890      1119

    accuracy                         0.5897      2747
   macro avg     0.5764    0.5856    0.5796      2747
weighted avg     0.5943    0.5897    0.5910      2747


================================================================================
PRIORITY - LINEAR SVM
================================================================================
              precision    recall  f1-score   support

        high     0.6327    0.6321    0.6324      1060
         low     0.4811    0.5599    0.5175       568
      medium     0.6154    0.5648    0.5890      1119

    accuracy                         0.5897      2747
   macro avg     0.5764    0.5856    0.5796      2747
weighted avg     0.5943    0.5897    0.5910      2747


================================================================================
PRIORITY - NAIVE BAYES
================================================================================
              precision    recall  f1-score   support

        high     0.5397    0.6226    0.5782      1060
         low     0.6909    0.0669    0.1220       568
      medium     0.5031    0.6604    0.5711      1119

    accuracy                         0.5231      2747
   macro avg     0.5779    0.4500    0.4238      2747
weighted avg     0.5560    0.5231    0.4810      2747

In [84]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC

param_grid = {
    'C': [0.01, 0.1, 0.5, 1, 2, 5, 10]
}

queue_grid = GridSearchCV(
    LinearSVC(class_weight='balanced'),
    param_grid,
    scoring='f1_macro',
    cv=5,
    n_jobs=-1
)

queue_grid.fit(X_train_final, y_queue_train)

print(queue_grid.best_params_)
print(queue_grid.best_score_)

{'C': 5}
0.6063792189910053

In [85]:
priority_grid = GridSearchCV(
    LinearSVC(class_weight='balanced'),
    param_grid,
    scoring='f1_macro',
    cv=5,
    n_jobs=-1
)

priority_grid.fit(X_train_final, y_priority_train)

print(priority_grid.best_params_)
print(priority_grid.best_score_)

{'C': 5}
0.6201520296159387

In [86]:
from sklearn.svm import LinearSVC

queue_svm_best = LinearSVC(
    C=5,
    class_weight='balanced'
)

priority_svm_best = LinearSVC(
    C=5,
    class_weight='balanced'
)

queue_svm_best.fit(X_train_final, y_queue_train)

priority_svm_best.fit(X_train_final, y_priority_train)

LinearSVC(C=5, class_weight='balanced')

In [87]:
queue_svm_best_pred = queue_svm_best.predict(X_test_final)

priority_svm_best_pred = priority_svm_best.predict(X_test_final)

In [88]:
from sklearn.metrics import classification_report

print("QUEUE")
print(classification_report(
    y_queue_test,
    queue_svm_best_pred,
    digits=4,
    zero_division=0
))

print("\nPRIORITY")
print(classification_report(
    y_priority_test,
    priority_svm_best_pred,
    digits=4,
    zero_division=0
))

QUEUE
                                 precision    recall  f1-score   support

           Billing and Payments     0.8208    0.8481    0.8342       270
               Customer Service     0.5489    0.5623    0.5556       409
                General Inquiry     0.7308    0.5135    0.6032        37
                Human Resources     0.7714    0.4737    0.5870        57
                     IT Support     0.5601    0.5932    0.5762       322
                Product Support     0.5833    0.5766    0.5800       522
          Returns and Exchanges     0.6423    0.5766    0.6077       137
            Sales and Pre-Sales     0.5506    0.5976    0.5731        82
Service Outages and Maintenance     0.7339    0.7845    0.7583       116
              Technical Support     0.6491    0.6491    0.6491       795

                       accuracy                         0.6305      2747
                      macro avg     0.6591    0.6175    0.6324      2747
                   weighted avg     0.6321    0.6305    0.6300      2747


PRIORITY
              precision    recall  f1-score   support

        high     0.6553    0.6868    0.6707      1060
         low     0.6038    0.5634    0.5829       568
      medium     0.6664    0.6586    0.6625      1119

    accuracy                         0.6498      2747
   macro avg     0.6418    0.6363    0.6387      2747
weighted avg     0.6491    0.6498    0.6492      2747

In [89]:
from sklearn.metrics import accuracy_score, f1_score

print("QUEUE")
print("Accuracy:", accuracy_score(y_queue_test, queue_svm_best_pred))
print("Macro F1:", f1_score(y_queue_test, queue_svm_best_pred, average='macro'))
print("Weighted F1:", f1_score(y_queue_test, queue_svm_best_pred, average='weighted'))

print("\nPRIORITY")
print("Accuracy:", accuracy_score(y_priority_test, priority_svm_best_pred))
print("Macro F1:", f1_score(y_priority_test, priority_svm_best_pred, average='macro'))
print("Weighted F1:", f1_score(y_priority_test, priority_svm_best_pred, average='weighted'))

QUEUE
Accuracy: 0.6305060065526028
Macro F1: 0.6324242814083546
Weighted F1: 0.6300411541142961

PRIORITY
Accuracy: 0.6497997815799054
Macro F1: 0.6386695175580768
Weighted F1: 0.6491732625581217